<?php
/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * GENERATED CODE WARNING
 * Generated by gapic-generator-php from the file
 * https://github.com/googleapis/googleapis/blob/master/google/cloud/retail/v2alpha/analytics_service.proto
 * Updates to the above are reflected here through a refresh process.
 *
 * @experimental
 */

namespace Google\Cloud\Retail\V2alpha\Client;

use Google\ApiCore\ApiException;
use Google\ApiCore\OperationResponse;
use Google\ApiCore\RetrySettings;
use Google\Cloud\Retail\V2alpha\ExportAnalyticsMetricsRequest;
use Google\Cloud\Retail\V2alpha\ExportAnalyticsMetricsResponse;
use Google\Cloud\Retail\V2alpha\ExportMetadata;
use Google\LongRunning\Client\OperationsClient;
use Google\LongRunning\Operation;
use GuzzleHttp\Promise\PromiseInterface;

/**
 * Service Description: Service for managing & accessing retail search business metric.
 * Retail recommendation business metric is currently not available.
 *
 * This interface defines the methods available for calling the backing service
 * API.
 *
 * @experimental
 *
 * @method PromiseInterface<OperationResponse> exportAnalyticsMetricsAsync(ExportAnalyticsMetricsRequest $request, array $optionalArgs = [])
 */
interface AnalyticsServiceClientInterface
{
    /**
     * Return an OperationsClient object with the same endpoint as $this.
     *
     * @return OperationsClient
     *
     * @experimental
     */
    public function getOperationsClient();

    /**
     * Resume an existing long running operation that was previously started by a long
     * running API method. If $methodName is not provided, or does not match a long
     * running API method, then the operation can still be resumed, but the
     * OperationResponse object will not deserialize the final response.
     *
     * @param string $operationName The name of the long running operation
     * @param string $methodName    The name of the method used to start the operation
     *
     * @return OperationResponse
     *
     * @experimental
     */
    public function resumeOperation($operationName, $methodName = null);

    /**
     * Exports analytics metrics.
     *
     * `Operation.response` is of type `ExportAnalyticsMetricsResponse`.
     * `Operation.metadata` is of type `ExportMetadata`.
     *
     * The async variant is
     * {@see AnalyticsServiceClient::exportAnalyticsMetricsAsync()} .
     *
     * @example samples/V2alpha/AnalyticsServiceClient/export_analytics_metrics.php
     *
     * @param ExportAnalyticsMetricsRequest $request     A request to house fields associated with the call.
     * @param array                         $callOptions {
     *     Optional.
     *
     *     @type RetrySettings|array $retrySettings
     *           Retry settings to use for this call. Can be a {@see RetrySettings} object, or an
     *           associative array of retry settings parameters. See the documentation on
     *           {@see RetrySettings} for example usage.
     * }
     *
     * @return OperationResponse<ExportAnalyticsMetricsResponse>
     *
     * @throws ApiException Thrown if the API call fails.
     *
     * @experimental
     */
    public function exportAnalyticsMetrics(ExportAnalyticsMetricsRequest $request, array $callOptions = []): OperationResponse;
}
