<?php
/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * GENERATED CODE WARNING
 * Generated by gapic-generator-php from the file
 * https://github.com/googleapis/googleapis/blob/master/google/cloud/retail/v2alpha/merchant_center_account_link_service.proto
 * Updates to the above are reflected here through a refresh process.
 *
 * @experimental
 */

namespace Google\Cloud\Retail\V2alpha\Client;

use Google\ApiCore\ApiException;
use Google\ApiCore\OperationResponse;
use Google\ApiCore\RetrySettings;
use Google\Cloud\Retail\V2alpha\CreateMerchantCenterAccountLinkRequest;
use Google\Cloud\Retail\V2alpha\DeleteMerchantCenterAccountLinkRequest;
use Google\Cloud\Retail\V2alpha\ListMerchantCenterAccountLinksRequest;
use Google\Cloud\Retail\V2alpha\ListMerchantCenterAccountLinksResponse;
use Google\Cloud\Retail\V2alpha\MerchantCenterAccountLink;
use Google\LongRunning\Client\OperationsClient;
use Google\LongRunning\Operation;
use GuzzleHttp\Promise\PromiseInterface;

/**
 * Service Description: Merchant Center Link service to link a Branch to a Merchant Center Account.
 *
 * This interface defines the methods available for calling the backing service
 * API.
 *
 * @experimental
 *
 * @method PromiseInterface<OperationResponse> createMerchantCenterAccountLinkAsync(CreateMerchantCenterAccountLinkRequest $request, array $optionalArgs = [])
 * @method PromiseInterface<void> deleteMerchantCenterAccountLinkAsync(DeleteMerchantCenterAccountLinkRequest $request, array $optionalArgs = [])
 * @method PromiseInterface<ListMerchantCenterAccountLinksResponse> listMerchantCenterAccountLinksAsync(ListMerchantCenterAccountLinksRequest $request, array $optionalArgs = [])
 */
interface MerchantCenterAccountLinkServiceClientInterface
{
    /**
     * Return an OperationsClient object with the same endpoint as $this.
     *
     * @return OperationsClient
     *
     * @experimental
     */
    public function getOperationsClient();

    /**
     * Resume an existing long running operation that was previously started by a long
     * running API method. If $methodName is not provided, or does not match a long
     * running API method, then the operation can still be resumed, but the
     * OperationResponse object will not deserialize the final response.
     *
     * @param string $operationName The name of the long running operation
     * @param string $methodName    The name of the method used to start the operation
     *
     * @return OperationResponse
     *
     * @experimental
     */
    public function resumeOperation($operationName, $methodName = null);

    /**
     * Creates a
     * [MerchantCenterAccountLink][google.cloud.retail.v2alpha.MerchantCenterAccountLink].
     *
     * The async variant is
     * {@see MerchantCenterAccountLinkServiceClient::createMerchantCenterAccountLinkAsync()}
     * .
     *
     * @example samples/V2alpha/MerchantCenterAccountLinkServiceClient/create_merchant_center_account_link.php
     *
     * @param CreateMerchantCenterAccountLinkRequest $request     A request to house fields associated with the call.
     * @param array                                  $callOptions {
     *     Optional.
     *
     *     @type RetrySettings|array $retrySettings
     *           Retry settings to use for this call. Can be a {@see RetrySettings} object, or an
     *           associative array of retry settings parameters. See the documentation on
     *           {@see RetrySettings} for example usage.
     * }
     *
     * @return OperationResponse<MerchantCenterAccountLink>
     *
     * @throws ApiException Thrown if the API call fails.
     *
     * @experimental
     */
    public function createMerchantCenterAccountLink(CreateMerchantCenterAccountLinkRequest $request, array $callOptions = []): OperationResponse;

    /**
     * Deletes a
     * [MerchantCenterAccountLink][google.cloud.retail.v2alpha.MerchantCenterAccountLink].
     * If the
     * [MerchantCenterAccountLink][google.cloud.retail.v2alpha.MerchantCenterAccountLink]
     * to delete does not exist, a NOT_FOUND error is returned.
     *
     * The async variant is
     * {@see MerchantCenterAccountLinkServiceClient::deleteMerchantCenterAccountLinkAsync()}
     * .
     *
     * @example samples/V2alpha/MerchantCenterAccountLinkServiceClient/delete_merchant_center_account_link.php
     *
     * @param DeleteMerchantCenterAccountLinkRequest $request     A request to house fields associated with the call.
     * @param array                                  $callOptions {
     *     Optional.
     *
     *     @type RetrySettings|array $retrySettings
     *           Retry settings to use for this call. Can be a {@see RetrySettings} object, or an
     *           associative array of retry settings parameters. See the documentation on
     *           {@see RetrySettings} for example usage.
     * }
     *
     * @throws ApiException Thrown if the API call fails.
     *
     * @experimental
     */
    public function deleteMerchantCenterAccountLink(DeleteMerchantCenterAccountLinkRequest $request, array $callOptions = []): void;

    /**
     * Lists all
     * [MerchantCenterAccountLink][google.cloud.retail.v2alpha.MerchantCenterAccountLink]s
     * under the specified parent [Catalog][google.cloud.retail.v2alpha.Catalog].
     *
     * The async variant is
     * {@see MerchantCenterAccountLinkServiceClient::listMerchantCenterAccountLinksAsync()}
     * .
     *
     * @example samples/V2alpha/MerchantCenterAccountLinkServiceClient/list_merchant_center_account_links.php
     *
     * @param ListMerchantCenterAccountLinksRequest $request     A request to house fields associated with the call.
     * @param array                                 $callOptions {
     *     Optional.
     *
     *     @type RetrySettings|array $retrySettings
     *           Retry settings to use for this call. Can be a {@see RetrySettings} object, or an
     *           associative array of retry settings parameters. See the documentation on
     *           {@see RetrySettings} for example usage.
     * }
     *
     * @return ListMerchantCenterAccountLinksResponse
     *
     * @throws ApiException Thrown if the API call fails.
     *
     * @experimental
     */
    public function listMerchantCenterAccountLinks(ListMerchantCenterAccountLinksRequest $request, array $callOptions = []): ListMerchantCenterAccountLinksResponse;
}
