<?php
/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * GENERATED CODE WARNING
 * Generated by gapic-generator-php from the file
 * https://github.com/googleapis/googleapis/blob/master/google/cloud/retail/v2alpha/model_service.proto
 * Updates to the above are reflected here through a refresh process.
 *
 * @experimental
 */

namespace Google\Cloud\Retail\V2alpha\Client;

use Google\ApiCore\ApiException;
use Google\ApiCore\OperationResponse;
use Google\ApiCore\PagedListResponse;
use Google\ApiCore\RetrySettings;
use Google\Cloud\Retail\V2alpha\CreateModelRequest;
use Google\Cloud\Retail\V2alpha\DeleteModelRequest;
use Google\Cloud\Retail\V2alpha\GetModelRequest;
use Google\Cloud\Retail\V2alpha\ListModelsRequest;
use Google\Cloud\Retail\V2alpha\Model;
use Google\Cloud\Retail\V2alpha\PauseModelRequest;
use Google\Cloud\Retail\V2alpha\ResumeModelRequest;
use Google\Cloud\Retail\V2alpha\TuneModelRequest;
use Google\Cloud\Retail\V2alpha\TuneModelResponse;
use Google\Cloud\Retail\V2alpha\UpdateModelRequest;
use Google\LongRunning\Client\OperationsClient;
use Google\LongRunning\Operation;
use GuzzleHttp\Promise\PromiseInterface;

/**
 * Service Description: Service for performing CRUD operations on models.
 * Recommendation models contain all the metadata necessary to generate a set of
 * models for the `Predict()` API. A model is queried
 * indirectly via a ServingConfig, which associates a model with a
 * given Placement (e.g. Frequently Bought Together on Home Page).
 *
 * This service allows you to do the following:
 *
 * * Initiate training of a model.
 * * Pause training of an existing model.
 * * List all the available models along with their metadata.
 * * Control their tuning schedule.
 *
 * This interface defines the methods available for calling the backing service
 * API.
 *
 * @experimental
 *
 * @method PromiseInterface<OperationResponse> createModelAsync(CreateModelRequest $request, array $optionalArgs = [])
 * @method PromiseInterface<void> deleteModelAsync(DeleteModelRequest $request, array $optionalArgs = [])
 * @method PromiseInterface<Model> getModelAsync(GetModelRequest $request, array $optionalArgs = [])
 * @method PromiseInterface<PagedListResponse> listModelsAsync(ListModelsRequest $request, array $optionalArgs = [])
 * @method PromiseInterface<Model> pauseModelAsync(PauseModelRequest $request, array $optionalArgs = [])
 * @method PromiseInterface<Model> resumeModelAsync(ResumeModelRequest $request, array $optionalArgs = [])
 * @method PromiseInterface<OperationResponse> tuneModelAsync(TuneModelRequest $request, array $optionalArgs = [])
 * @method PromiseInterface<Model> updateModelAsync(UpdateModelRequest $request, array $optionalArgs = [])
 */
interface ModelServiceClientInterface
{
    /**
     * Return an OperationsClient object with the same endpoint as $this.
     *
     * @return OperationsClient
     *
     * @experimental
     */
    public function getOperationsClient();

    /**
     * Resume an existing long running operation that was previously started by a long
     * running API method. If $methodName is not provided, or does not match a long
     * running API method, then the operation can still be resumed, but the
     * OperationResponse object will not deserialize the final response.
     *
     * @param string $operationName The name of the long running operation
     * @param string $methodName    The name of the method used to start the operation
     *
     * @return OperationResponse
     *
     * @experimental
     */
    public function resumeOperation($operationName, $methodName = null);

    /**
     * Creates a new model.
     *
     * The async variant is {@see ModelServiceClient::createModelAsync()} .
     *
     * @example samples/V2alpha/ModelServiceClient/create_model.php
     *
     * @param CreateModelRequest $request     A request to house fields associated with the call.
     * @param array              $callOptions {
     *     Optional.
     *
     *     @type RetrySettings|array $retrySettings
     *           Retry settings to use for this call. Can be a {@see RetrySettings} object, or an
     *           associative array of retry settings parameters. See the documentation on
     *           {@see RetrySettings} for example usage.
     * }
     *
     * @return OperationResponse<Model>
     *
     * @throws ApiException Thrown if the API call fails.
     *
     * @experimental
     */
    public function createModel(CreateModelRequest $request, array $callOptions = []): OperationResponse;

    /**
     * Deletes an existing model.
     *
     * The async variant is {@see ModelServiceClient::deleteModelAsync()} .
     *
     * @example samples/V2alpha/ModelServiceClient/delete_model.php
     *
     * @param DeleteModelRequest $request     A request to house fields associated with the call.
     * @param array              $callOptions {
     *     Optional.
     *
     *     @type RetrySettings|array $retrySettings
     *           Retry settings to use for this call. Can be a {@see RetrySettings} object, or an
     *           associative array of retry settings parameters. See the documentation on
     *           {@see RetrySettings} for example usage.
     * }
     *
     * @throws ApiException Thrown if the API call fails.
     *
     * @experimental
     */
    public function deleteModel(DeleteModelRequest $request, array $callOptions = []): void;

    /**
     * Gets a model.
     *
     * The async variant is {@see ModelServiceClient::getModelAsync()} .
     *
     * @example samples/V2alpha/ModelServiceClient/get_model.php
     *
     * @param GetModelRequest $request     A request to house fields associated with the call.
     * @param array           $callOptions {
     *     Optional.
     *
     *     @type RetrySettings|array $retrySettings
     *           Retry settings to use for this call. Can be a {@see RetrySettings} object, or an
     *           associative array of retry settings parameters. See the documentation on
     *           {@see RetrySettings} for example usage.
     * }
     *
     * @return Model
     *
     * @throws ApiException Thrown if the API call fails.
     *
     * @experimental
     */
    public function getModel(GetModelRequest $request, array $callOptions = []): Model;

    /**
     * Lists all the models linked to this event store.
     *
     * The async variant is {@see ModelServiceClient::listModelsAsync()} .
     *
     * @example samples/V2alpha/ModelServiceClient/list_models.php
     *
     * @param ListModelsRequest $request     A request to house fields associated with the call.
     * @param array             $callOptions {
     *     Optional.
     *
     *     @type RetrySettings|array $retrySettings
     *           Retry settings to use for this call. Can be a {@see RetrySettings} object, or an
     *           associative array of retry settings parameters. See the documentation on
     *           {@see RetrySettings} for example usage.
     * }
     *
     * @return PagedListResponse
     *
     * @throws ApiException Thrown if the API call fails.
     *
     * @experimental
     */
    public function listModels(ListModelsRequest $request, array $callOptions = []): PagedListResponse;

    /**
     * Pauses the training of an existing model.
     *
     * The async variant is {@see ModelServiceClient::pauseModelAsync()} .
     *
     * @example samples/V2alpha/ModelServiceClient/pause_model.php
     *
     * @param PauseModelRequest $request     A request to house fields associated with the call.
     * @param array             $callOptions {
     *     Optional.
     *
     *     @type RetrySettings|array $retrySettings
     *           Retry settings to use for this call. Can be a {@see RetrySettings} object, or an
     *           associative array of retry settings parameters. See the documentation on
     *           {@see RetrySettings} for example usage.
     * }
     *
     * @return Model
     *
     * @throws ApiException Thrown if the API call fails.
     *
     * @experimental
     */
    public function pauseModel(PauseModelRequest $request, array $callOptions = []): Model;

    /**
     * Resumes the training of an existing model.
     *
     * The async variant is {@see ModelServiceClient::resumeModelAsync()} .
     *
     * @example samples/V2alpha/ModelServiceClient/resume_model.php
     *
     * @param ResumeModelRequest $request     A request to house fields associated with the call.
     * @param array              $callOptions {
     *     Optional.
     *
     *     @type RetrySettings|array $retrySettings
     *           Retry settings to use for this call. Can be a {@see RetrySettings} object, or an
     *           associative array of retry settings parameters. See the documentation on
     *           {@see RetrySettings} for example usage.
     * }
     *
     * @return Model
     *
     * @throws ApiException Thrown if the API call fails.
     *
     * @experimental
     */
    public function resumeModel(ResumeModelRequest $request, array $callOptions = []): Model;

    /**
     * Tunes an existing model.
     *
     * The async variant is {@see ModelServiceClient::tuneModelAsync()} .
     *
     * @example samples/V2alpha/ModelServiceClient/tune_model.php
     *
     * @param TuneModelRequest $request     A request to house fields associated with the call.
     * @param array            $callOptions {
     *     Optional.
     *
     *     @type RetrySettings|array $retrySettings
     *           Retry settings to use for this call. Can be a {@see RetrySettings} object, or an
     *           associative array of retry settings parameters. See the documentation on
     *           {@see RetrySettings} for example usage.
     * }
     *
     * @return OperationResponse<TuneModelResponse>
     *
     * @throws ApiException Thrown if the API call fails.
     *
     * @experimental
     */
    public function tuneModel(TuneModelRequest $request, array $callOptions = []): OperationResponse;

    /**
     * Update of model metadata. Only fields that
     * currently can be updated are: `filtering_option` and
     * `periodic_tuning_state`.
     * If other values are provided, this API method ignores them.
     *
     * The async variant is {@see ModelServiceClient::updateModelAsync()} .
     *
     * @example samples/V2alpha/ModelServiceClient/update_model.php
     *
     * @param UpdateModelRequest $request     A request to house fields associated with the call.
     * @param array              $callOptions {
     *     Optional.
     *
     *     @type RetrySettings|array $retrySettings
     *           Retry settings to use for this call. Can be a {@see RetrySettings} object, or an
     *           associative array of retry settings parameters. See the documentation on
     *           {@see RetrySettings} for example usage.
     * }
     *
     * @return Model
     *
     * @throws ApiException Thrown if the API call fails.
     *
     * @experimental
     */
    public function updateModel(UpdateModelRequest $request, array $callOptions = []): Model;
}
