<?php
/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * GENERATED CODE WARNING
 * Generated by gapic-generator-php from the file
 * https://github.com/googleapis/googleapis/blob/master/google/cloud/retail/v2alpha/serving_config_service.proto
 * Updates to the above are reflected here through a refresh process.
 *
 * @experimental
 */

namespace Google\Cloud\Retail\V2alpha\Client;

use Google\ApiCore\ApiException;
use Google\ApiCore\PagedListResponse;
use Google\ApiCore\RetrySettings;
use Google\Cloud\Retail\V2alpha\AddControlRequest;
use Google\Cloud\Retail\V2alpha\CreateServingConfigRequest;
use Google\Cloud\Retail\V2alpha\DeleteServingConfigRequest;
use Google\Cloud\Retail\V2alpha\GetServingConfigRequest;
use Google\Cloud\Retail\V2alpha\ListServingConfigsRequest;
use Google\Cloud\Retail\V2alpha\RemoveControlRequest;
use Google\Cloud\Retail\V2alpha\ServingConfig;
use Google\Cloud\Retail\V2alpha\UpdateServingConfigRequest;
use GuzzleHttp\Promise\PromiseInterface;

/**
 * Service Description: Service for modifying ServingConfig.
 *
 * This interface defines the methods available for calling the backing service
 * API.
 *
 * @experimental
 *
 * @method PromiseInterface<ServingConfig> addControlAsync(AddControlRequest $request, array $optionalArgs = [])
 * @method PromiseInterface<ServingConfig> createServingConfigAsync(CreateServingConfigRequest $request, array $optionalArgs = [])
 * @method PromiseInterface<void> deleteServingConfigAsync(DeleteServingConfigRequest $request, array $optionalArgs = [])
 * @method PromiseInterface<ServingConfig> getServingConfigAsync(GetServingConfigRequest $request, array $optionalArgs = [])
 * @method PromiseInterface<PagedListResponse> listServingConfigsAsync(ListServingConfigsRequest $request, array $optionalArgs = [])
 * @method PromiseInterface<ServingConfig> removeControlAsync(RemoveControlRequest $request, array $optionalArgs = [])
 * @method PromiseInterface<ServingConfig> updateServingConfigAsync(UpdateServingConfigRequest $request, array $optionalArgs = [])
 */
interface ServingConfigServiceClientInterface
{
    /**
     * Enables a Control on the specified ServingConfig.
     * The control is added in the last position of the list of controls
     * it belongs to (e.g. if it's a facet spec control it will be applied
     * in the last position of servingConfig.facetSpecIds)
     * Returns a ALREADY_EXISTS error if the control has already been applied.
     * Returns a FAILED_PRECONDITION error if the addition could exceed maximum
     * number of control allowed for that type of control.
     *
     * The async variant is {@see ServingConfigServiceClient::addControlAsync()} .
     *
     * @example samples/V2alpha/ServingConfigServiceClient/add_control.php
     *
     * @param AddControlRequest $request     A request to house fields associated with the call.
     * @param array             $callOptions {
     *     Optional.
     *
     *     @type RetrySettings|array $retrySettings
     *           Retry settings to use for this call. Can be a {@see RetrySettings} object, or an
     *           associative array of retry settings parameters. See the documentation on
     *           {@see RetrySettings} for example usage.
     * }
     *
     * @return ServingConfig
     *
     * @throws ApiException Thrown if the API call fails.
     *
     * @experimental
     */
    public function addControl(AddControlRequest $request, array $callOptions = []): ServingConfig;

    /**
     * Creates a ServingConfig.
     *
     * A maximum of 100
     * [ServingConfig][google.cloud.retail.v2alpha.ServingConfig]s are allowed in
     * a [Catalog][google.cloud.retail.v2alpha.Catalog], otherwise a
     * FAILED_PRECONDITION error is returned.
     *
     * The async variant is
     * {@see ServingConfigServiceClient::createServingConfigAsync()} .
     *
     * @example samples/V2alpha/ServingConfigServiceClient/create_serving_config.php
     *
     * @param CreateServingConfigRequest $request     A request to house fields associated with the call.
     * @param array                      $callOptions {
     *     Optional.
     *
     *     @type RetrySettings|array $retrySettings
     *           Retry settings to use for this call. Can be a {@see RetrySettings} object, or an
     *           associative array of retry settings parameters. See the documentation on
     *           {@see RetrySettings} for example usage.
     * }
     *
     * @return ServingConfig
     *
     * @throws ApiException Thrown if the API call fails.
     *
     * @experimental
     */
    public function createServingConfig(CreateServingConfigRequest $request, array $callOptions = []): ServingConfig;

    /**
     * Deletes a ServingConfig.
     *
     * Returns a NotFound error if the ServingConfig does not exist.
     *
     * The async variant is
     * {@see ServingConfigServiceClient::deleteServingConfigAsync()} .
     *
     * @example samples/V2alpha/ServingConfigServiceClient/delete_serving_config.php
     *
     * @param DeleteServingConfigRequest $request     A request to house fields associated with the call.
     * @param array                      $callOptions {
     *     Optional.
     *
     *     @type RetrySettings|array $retrySettings
     *           Retry settings to use for this call. Can be a {@see RetrySettings} object, or an
     *           associative array of retry settings parameters. See the documentation on
     *           {@see RetrySettings} for example usage.
     * }
     *
     * @throws ApiException Thrown if the API call fails.
     *
     * @experimental
     */
    public function deleteServingConfig(DeleteServingConfigRequest $request, array $callOptions = []): void;

    /**
     * Gets a ServingConfig.
     *
     * Returns a NotFound error if the ServingConfig does not exist.
     *
     * The async variant is {@see ServingConfigServiceClient::getServingConfigAsync()}
     * .
     *
     * @example samples/V2alpha/ServingConfigServiceClient/get_serving_config.php
     *
     * @param GetServingConfigRequest $request     A request to house fields associated with the call.
     * @param array                   $callOptions {
     *     Optional.
     *
     *     @type RetrySettings|array $retrySettings
     *           Retry settings to use for this call. Can be a {@see RetrySettings} object, or an
     *           associative array of retry settings parameters. See the documentation on
     *           {@see RetrySettings} for example usage.
     * }
     *
     * @return ServingConfig
     *
     * @throws ApiException Thrown if the API call fails.
     *
     * @experimental
     */
    public function getServingConfig(GetServingConfigRequest $request, array $callOptions = []): ServingConfig;

    /**
     * Lists all ServingConfigs linked to this catalog.
     *
     * The async variant is
     * {@see ServingConfigServiceClient::listServingConfigsAsync()} .
     *
     * @example samples/V2alpha/ServingConfigServiceClient/list_serving_configs.php
     *
     * @param ListServingConfigsRequest $request     A request to house fields associated with the call.
     * @param array                     $callOptions {
     *     Optional.
     *
     *     @type RetrySettings|array $retrySettings
     *           Retry settings to use for this call. Can be a {@see RetrySettings} object, or an
     *           associative array of retry settings parameters. See the documentation on
     *           {@see RetrySettings} for example usage.
     * }
     *
     * @return PagedListResponse
     *
     * @throws ApiException Thrown if the API call fails.
     *
     * @experimental
     */
    public function listServingConfigs(ListServingConfigsRequest $request, array $callOptions = []): PagedListResponse;

    /**
     * Disables a Control on the specified ServingConfig.
     * The control is removed from the ServingConfig.
     * Returns a NOT_FOUND error if the Control is not enabled for the
     * ServingConfig.
     *
     * The async variant is {@see ServingConfigServiceClient::removeControlAsync()} .
     *
     * @example samples/V2alpha/ServingConfigServiceClient/remove_control.php
     *
     * @param RemoveControlRequest $request     A request to house fields associated with the call.
     * @param array                $callOptions {
     *     Optional.
     *
     *     @type RetrySettings|array $retrySettings
     *           Retry settings to use for this call. Can be a {@see RetrySettings} object, or an
     *           associative array of retry settings parameters. See the documentation on
     *           {@see RetrySettings} for example usage.
     * }
     *
     * @return ServingConfig
     *
     * @throws ApiException Thrown if the API call fails.
     *
     * @experimental
     */
    public function removeControl(RemoveControlRequest $request, array $callOptions = []): ServingConfig;

    /**
     * Updates a ServingConfig.
     *
     * The async variant is
     * {@see ServingConfigServiceClient::updateServingConfigAsync()} .
     *
     * @example samples/V2alpha/ServingConfigServiceClient/update_serving_config.php
     *
     * @param UpdateServingConfigRequest $request     A request to house fields associated with the call.
     * @param array                      $callOptions {
     *     Optional.
     *
     *     @type RetrySettings|array $retrySettings
     *           Retry settings to use for this call. Can be a {@see RetrySettings} object, or an
     *           associative array of retry settings parameters. See the documentation on
     *           {@see RetrySettings} for example usage.
     * }
     *
     * @return ServingConfig
     *
     * @throws ApiException Thrown if the API call fails.
     *
     * @experimental
     */
    public function updateServingConfig(UpdateServingConfigRequest $request, array $callOptions = []): ServingConfig;
}
