<?php
/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
declare(strict_types=1);

namespace Google\Generator\Tests\Unit\PostProcessor;

use Google\Api\RoutingRule;
use PHPUnit\Framework\TestCase;
use Google\PostProcessor\ProtobufNoCheckInHeaderProcessor;
use Google\Protobuf\RepeatedField;
use phpDocumentor\Reflection\DocBlockFactory;
use ReflectionClass;
use ReflectionMethod;

final class ProtobufNoCheckInHeaderProcessorTest extends TestCase
{
    private $classContents = <<<EOL
<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bar.proto

class Bar
{
    /**
     * The constructor
     */
    public function __construct(private RepeatedField \$foo)
    {
    }

    /**
     * Empty method
     */
    public function bar()
    {
    }
}
EOL;

    /**
     * @runInSeparateProcess
     */
    public function testRemoveNoCheckInHeader()
    {
        $this->assertTrue($this->classContainsNoCheckInHeader($this->classContents));
        $processor = new ProtobufNoCheckInHeaderProcessor($this->classContents);
        $processor->removeNoCheckInHeader();
        $newClassContents = $processor->getContents();
        $this->assertFalse($this->classContainsNoCheckInHeader($newClassContents));
    }

    /**
     * @runInSeparateProcess
     */
    public function testRemoveNoCheckInHeaderWithProtobufMessage()
    {
        $protobufMessage = __DIR__ . '/../../../generated/Google/Api/RoutingRule.php';

        $addFragmentUtil = new ProtobufNoCheckInHeaderProcessor(file_get_contents($protobufMessage));

        // Fix the deprecations
        $addFragmentUtil->removeNoCheckInHeader();
        $newClassContents = $addFragmentUtil->getContents();
        $this->assertFalse($this->classContainsNoCheckInHeader($newClassContents));
    }

    /**
     * @runInSeparateProcess
     */
    public function testProtobufDeprecationProcessor()
    {
        $tmpDir = sys_get_temp_dir() . '/test-fragment-injection-processor-' . rand();
        mkdir($tmpDir . '/proto/src', 0777, true);
        file_put_contents($toFile = $tmpDir . '/proto/src/Bar.php', $this->classContents);

        ProtobufNoCheckInHeaderProcessor::run($tmpDir);

        // Verify the deprecations were fixed
        $newClassContents = file_get_contents($toFile);
        $this->assertFalse($this->classContainsNoCheckInHeader($newClassContents));

        // Verify post-processor output
        $this->expectOutputString('No Check-In Header removed in ' . $toFile . PHP_EOL);
    }

    private function classContainsNoCheckInHeader(string $classContents): bool
    {
        $tokens = token_get_all($classContents);
        foreach ($tokens as $token) {
            if (is_array($token)
                && $token[0] === T_COMMENT
                && str_contains($token[1], 'NO CHECKED-IN PROTOBUF GENCODE')) {
                return true;
            }
        }
        return false;
    }
}
