<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc/service_config/service_config.proto

namespace Grpc\Service_config;

if (false) {
    /**
     * This class is deprecated. Use Grpc\Service_config\WeightedTargetLoadBalancingPolicyConfig\Target instead.
     * @deprecated
     */
    class WeightedTargetLoadBalancingPolicyConfig_Target {}
}
class_exists(WeightedTargetLoadBalancingPolicyConfig\Target::class);
@trigger_error('Grpc\Service_config\WeightedTargetLoadBalancingPolicyConfig_Target is deprecated and will be removed in the next major release. Use Grpc\Service_config\WeightedTargetLoadBalancingPolicyConfig\Target instead', E_USER_DEPRECATED);

