<?php
/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * GENERATED CODE WARNING
 * Generated by gapic-generator-php from the file
 * https://github.com/googleapis/googleapis/blob/master/google/cloud/dataproc/v1/session_templates.proto
 * Updates to the above are reflected here through a refresh process.
 */

namespace Google\Cloud\Dataproc\V1\Client;

use Google\ApiCore\ApiException;
use Google\ApiCore\PagedListResponse;
use Google\ApiCore\RetrySettings;
use Google\Cloud\Dataproc\V1\CreateSessionTemplateRequest;
use Google\Cloud\Dataproc\V1\DeleteSessionTemplateRequest;
use Google\Cloud\Dataproc\V1\GetSessionTemplateRequest;
use Google\Cloud\Dataproc\V1\ListSessionTemplatesRequest;
use Google\Cloud\Dataproc\V1\SessionTemplate;
use Google\Cloud\Dataproc\V1\UpdateSessionTemplateRequest;
use Google\Cloud\Iam\V1\GetIamPolicyRequest;
use Google\Cloud\Iam\V1\Policy;
use Google\Cloud\Iam\V1\SetIamPolicyRequest;
use Google\Cloud\Iam\V1\TestIamPermissionsRequest;
use Google\Cloud\Iam\V1\TestIamPermissionsResponse;
use GuzzleHttp\Promise\PromiseInterface;

/**
 * Service Description: The SessionTemplateController provides methods to manage session templates.
 *
 * This interface defines the methods available for calling the backing service
 * API.
 *
 * @method PromiseInterface<SessionTemplate> createSessionTemplateAsync(CreateSessionTemplateRequest $request, array $optionalArgs = [])
 * @method PromiseInterface<void> deleteSessionTemplateAsync(DeleteSessionTemplateRequest $request, array $optionalArgs = [])
 * @method PromiseInterface<SessionTemplate> getSessionTemplateAsync(GetSessionTemplateRequest $request, array $optionalArgs = [])
 * @method PromiseInterface<PagedListResponse> listSessionTemplatesAsync(ListSessionTemplatesRequest $request, array $optionalArgs = [])
 * @method PromiseInterface<SessionTemplate> updateSessionTemplateAsync(UpdateSessionTemplateRequest $request, array $optionalArgs = [])
 * @method PromiseInterface<Policy> getIamPolicyAsync(GetIamPolicyRequest $request, array $optionalArgs = [])
 * @method PromiseInterface<Policy> setIamPolicyAsync(SetIamPolicyRequest $request, array $optionalArgs = [])
 * @method PromiseInterface<TestIamPermissionsResponse> testIamPermissionsAsync(TestIamPermissionsRequest $request, array $optionalArgs = [])
 */
interface SessionTemplateControllerClientInterface
{
    /**
     * Create a session template synchronously.
     *
     * The async variant is
     * {@see SessionTemplateControllerClient::createSessionTemplateAsync()} .
     *
     * @example samples/V1/SessionTemplateControllerClient/create_session_template.php
     *
     * @param CreateSessionTemplateRequest $request     A request to house fields associated with the call.
     * @param array                        $callOptions {
     *     Optional.
     *
     *     @type RetrySettings|array $retrySettings
     *           Retry settings to use for this call. Can be a {@see RetrySettings} object, or an
     *           associative array of retry settings parameters. See the documentation on
     *           {@see RetrySettings} for example usage.
     * }
     *
     * @return SessionTemplate
     *
     * @throws ApiException Thrown if the API call fails.
     */
    public function createSessionTemplate(CreateSessionTemplateRequest $request, array $callOptions = []): SessionTemplate;

    /**
     * Deletes a session template.
     *
     * The async variant is
     * {@see SessionTemplateControllerClient::deleteSessionTemplateAsync()} .
     *
     * @example samples/V1/SessionTemplateControllerClient/delete_session_template.php
     *
     * @param DeleteSessionTemplateRequest $request     A request to house fields associated with the call.
     * @param array                        $callOptions {
     *     Optional.
     *
     *     @type RetrySettings|array $retrySettings
     *           Retry settings to use for this call. Can be a {@see RetrySettings} object, or an
     *           associative array of retry settings parameters. See the documentation on
     *           {@see RetrySettings} for example usage.
     * }
     *
     * @throws ApiException Thrown if the API call fails.
     */
    public function deleteSessionTemplate(DeleteSessionTemplateRequest $request, array $callOptions = []): void;

    /**
     * Gets the resource representation for a session template.
     *
     * The async variant is
     * {@see SessionTemplateControllerClient::getSessionTemplateAsync()} .
     *
     * @example samples/V1/SessionTemplateControllerClient/get_session_template.php
     *
     * @param GetSessionTemplateRequest $request     A request to house fields associated with the call.
     * @param array                     $callOptions {
     *     Optional.
     *
     *     @type RetrySettings|array $retrySettings
     *           Retry settings to use for this call. Can be a {@see RetrySettings} object, or an
     *           associative array of retry settings parameters. See the documentation on
     *           {@see RetrySettings} for example usage.
     * }
     *
     * @return SessionTemplate
     *
     * @throws ApiException Thrown if the API call fails.
     */
    public function getSessionTemplate(GetSessionTemplateRequest $request, array $callOptions = []): SessionTemplate;

    /**
     * Lists session templates.
     *
     * The async variant is
     * {@see SessionTemplateControllerClient::listSessionTemplatesAsync()} .
     *
     * @example samples/V1/SessionTemplateControllerClient/list_session_templates.php
     *
     * @param ListSessionTemplatesRequest $request     A request to house fields associated with the call.
     * @param array                       $callOptions {
     *     Optional.
     *
     *     @type RetrySettings|array $retrySettings
     *           Retry settings to use for this call. Can be a {@see RetrySettings} object, or an
     *           associative array of retry settings parameters. See the documentation on
     *           {@see RetrySettings} for example usage.
     * }
     *
     * @return PagedListResponse
     *
     * @throws ApiException Thrown if the API call fails.
     */
    public function listSessionTemplates(ListSessionTemplatesRequest $request, array $callOptions = []): PagedListResponse;

    /**
     * Updates the session template synchronously.
     *
     * The async variant is
     * {@see SessionTemplateControllerClient::updateSessionTemplateAsync()} .
     *
     * @example samples/V1/SessionTemplateControllerClient/update_session_template.php
     *
     * @param UpdateSessionTemplateRequest $request     A request to house fields associated with the call.
     * @param array                        $callOptions {
     *     Optional.
     *
     *     @type RetrySettings|array $retrySettings
     *           Retry settings to use for this call. Can be a {@see RetrySettings} object, or an
     *           associative array of retry settings parameters. See the documentation on
     *           {@see RetrySettings} for example usage.
     * }
     *
     * @return SessionTemplate
     *
     * @throws ApiException Thrown if the API call fails.
     */
    public function updateSessionTemplate(UpdateSessionTemplateRequest $request, array $callOptions = []): SessionTemplate;

    /**
     * Gets the access control policy for a resource. Returns an empty policy
     * if the resource exists and does not have a policy set.
     *
     * The async variant is {@see SessionTemplateControllerClient::getIamPolicyAsync()}
     * .
     *
     * @example samples/V1/SessionTemplateControllerClient/get_iam_policy.php
     *
     * @param GetIamPolicyRequest $request     A request to house fields associated with the call.
     * @param array               $callOptions {
     *     Optional.
     *
     *     @type RetrySettings|array $retrySettings
     *           Retry settings to use for this call. Can be a {@see RetrySettings} object, or an
     *           associative array of retry settings parameters. See the documentation on
     *           {@see RetrySettings} for example usage.
     * }
     *
     * @return Policy
     *
     * @throws ApiException Thrown if the API call fails.
     */
    public function getIamPolicy(GetIamPolicyRequest $request, array $callOptions = []): Policy;

    /**
     * Sets the access control policy on the specified resource. Replaces
     * any existing policy.
     *
     * Can return `NOT_FOUND`, `INVALID_ARGUMENT`, and `PERMISSION_DENIED`
     * errors.
     *
     * The async variant is {@see SessionTemplateControllerClient::setIamPolicyAsync()}
     * .
     *
     * @example samples/V1/SessionTemplateControllerClient/set_iam_policy.php
     *
     * @param SetIamPolicyRequest $request     A request to house fields associated with the call.
     * @param array               $callOptions {
     *     Optional.
     *
     *     @type RetrySettings|array $retrySettings
     *           Retry settings to use for this call. Can be a {@see RetrySettings} object, or an
     *           associative array of retry settings parameters. See the documentation on
     *           {@see RetrySettings} for example usage.
     * }
     *
     * @return Policy
     *
     * @throws ApiException Thrown if the API call fails.
     */
    public function setIamPolicy(SetIamPolicyRequest $request, array $callOptions = []): Policy;

    /**
     * Returns permissions that a caller has on the specified resource. If the
     * resource does not exist, this will return an empty set of
     * permissions, not a `NOT_FOUND` error.
     *
     * Note: This operation is designed to be used for building
     * permission-aware UIs and command-line tools, not for authorization
     * checking. This operation may "fail open" without warning.
     *
     * The async variant is
     * {@see SessionTemplateControllerClient::testIamPermissionsAsync()} .
     *
     * @example samples/V1/SessionTemplateControllerClient/test_iam_permissions.php
     *
     * @param TestIamPermissionsRequest $request     A request to house fields associated with the call.
     * @param array                     $callOptions {
     *     Optional.
     *
     *     @type RetrySettings|array $retrySettings
     *           Retry settings to use for this call. Can be a {@see RetrySettings} object, or an
     *           associative array of retry settings parameters. See the documentation on
     *           {@see RetrySettings} for example usage.
     * }
     *
     * @return TestIamPermissionsResponse
     *
     * @throws ApiException Thrown if the API call fails.
     */
    public function testIamPermissions(TestIamPermissionsRequest $request, array $callOptions = []): TestIamPermissionsResponse;
}
