<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc/service_config/service_config.proto

namespace Grpc\Service_config\LrsLoadBalancingPolicyConfig;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The locality for which this policy will report load.  Required.
 *
 * Generated from protobuf message <code>grpc.service_config.LrsLoadBalancingPolicyConfig.Locality</code>
 */
class Locality extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string region = 1;</code>
     */
    protected $region = '';
    /**
     * Generated from protobuf field <code>string zone = 2;</code>
     */
    protected $zone = '';
    /**
     * Generated from protobuf field <code>string subzone = 3;</code>
     */
    protected $subzone = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $region
     *     @type string $zone
     *     @type string $subzone
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Grpc\ServiceConfig\ServiceConfig::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string region = 1;</code>
     * @return string
     */
    public function getRegion()
    {
        return $this->region;
    }

    /**
     * Generated from protobuf field <code>string region = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRegion($var)
    {
        GPBUtil::checkString($var, true);
        $this->region = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string zone = 2;</code>
     * @return string
     */
    public function getZone()
    {
        return $this->zone;
    }

    /**
     * Generated from protobuf field <code>string zone = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setZone($var)
    {
        GPBUtil::checkString($var, true);
        $this->zone = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subzone = 3;</code>
     * @return string
     */
    public function getSubzone()
    {
        return $this->subzone;
    }

    /**
     * Generated from protobuf field <code>string subzone = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSubzone($var)
    {
        GPBUtil::checkString($var, true);
        $this->subzone = $var;

        return $this;
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Locality::class, \Grpc\Service_config\LrsLoadBalancingPolicyConfig_Locality::class);
