<?php
/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * GENERATED CODE WARNING
 * Generated by gapic-generator-php from the file
 * https://github.com/googleapis/googleapis/blob/master/google/cloud/talent/v4beta1/company_service.proto
 * Updates to the above are reflected here through a refresh process.
 *
 * @experimental
 */

namespace Google\Cloud\Talent\V4beta1\Client;

use Google\ApiCore\ApiException;
use Google\ApiCore\PagedListResponse;
use Google\ApiCore\RetrySettings;
use Google\Cloud\Talent\V4beta1\Company;
use Google\Cloud\Talent\V4beta1\CreateCompanyRequest;
use Google\Cloud\Talent\V4beta1\DeleteCompanyRequest;
use Google\Cloud\Talent\V4beta1\GetCompanyRequest;
use Google\Cloud\Talent\V4beta1\ListCompaniesRequest;
use Google\Cloud\Talent\V4beta1\UpdateCompanyRequest;
use GuzzleHttp\Promise\PromiseInterface;

/**
 * Service Description: A service that handles company management, including CRUD and enumeration.
 *
 * This interface defines the methods available for calling the backing service
 * API.
 *
 * @experimental
 *
 * @method PromiseInterface<Company> createCompanyAsync(CreateCompanyRequest $request, array $optionalArgs = [])
 * @method PromiseInterface<void> deleteCompanyAsync(DeleteCompanyRequest $request, array $optionalArgs = [])
 * @method PromiseInterface<Company> getCompanyAsync(GetCompanyRequest $request, array $optionalArgs = [])
 * @method PromiseInterface<PagedListResponse> listCompaniesAsync(ListCompaniesRequest $request, array $optionalArgs = [])
 * @method PromiseInterface<Company> updateCompanyAsync(UpdateCompanyRequest $request, array $optionalArgs = [])
 */
interface CompanyServiceClientInterface
{
    /**
     * Creates a new company entity.
     *
     * The async variant is {@see CompanyServiceClient::createCompanyAsync()} .
     *
     * @example samples/V4beta1/CompanyServiceClient/create_company.php
     *
     * @param CreateCompanyRequest $request     A request to house fields associated with the call.
     * @param array                $callOptions {
     *     Optional.
     *
     *     @type RetrySettings|array $retrySettings
     *           Retry settings to use for this call. Can be a {@see RetrySettings} object, or an
     *           associative array of retry settings parameters. See the documentation on
     *           {@see RetrySettings} for example usage.
     * }
     *
     * @return Company
     *
     * @throws ApiException Thrown if the API call fails.
     *
     * @experimental
     */
    public function createCompany(CreateCompanyRequest $request, array $callOptions = []): Company;

    /**
     * Deletes specified company.
     * Prerequisite: The company has no jobs associated with it.
     *
     * The async variant is {@see CompanyServiceClient::deleteCompanyAsync()} .
     *
     * @example samples/V4beta1/CompanyServiceClient/delete_company.php
     *
     * @param DeleteCompanyRequest $request     A request to house fields associated with the call.
     * @param array                $callOptions {
     *     Optional.
     *
     *     @type RetrySettings|array $retrySettings
     *           Retry settings to use for this call. Can be a {@see RetrySettings} object, or an
     *           associative array of retry settings parameters. See the documentation on
     *           {@see RetrySettings} for example usage.
     * }
     *
     * @throws ApiException Thrown if the API call fails.
     *
     * @experimental
     */
    public function deleteCompany(DeleteCompanyRequest $request, array $callOptions = []): void;

    /**
     * Retrieves specified company.
     *
     * The async variant is {@see CompanyServiceClient::getCompanyAsync()} .
     *
     * @example samples/V4beta1/CompanyServiceClient/get_company.php
     *
     * @param GetCompanyRequest $request     A request to house fields associated with the call.
     * @param array             $callOptions {
     *     Optional.
     *
     *     @type RetrySettings|array $retrySettings
     *           Retry settings to use for this call. Can be a {@see RetrySettings} object, or an
     *           associative array of retry settings parameters. See the documentation on
     *           {@see RetrySettings} for example usage.
     * }
     *
     * @return Company
     *
     * @throws ApiException Thrown if the API call fails.
     *
     * @experimental
     */
    public function getCompany(GetCompanyRequest $request, array $callOptions = []): Company;

    /**
     * Lists all companies associated with the project.
     *
     * The async variant is {@see CompanyServiceClient::listCompaniesAsync()} .
     *
     * @example samples/V4beta1/CompanyServiceClient/list_companies.php
     *
     * @param ListCompaniesRequest $request     A request to house fields associated with the call.
     * @param array                $callOptions {
     *     Optional.
     *
     *     @type RetrySettings|array $retrySettings
     *           Retry settings to use for this call. Can be a {@see RetrySettings} object, or an
     *           associative array of retry settings parameters. See the documentation on
     *           {@see RetrySettings} for example usage.
     * }
     *
     * @return PagedListResponse
     *
     * @throws ApiException Thrown if the API call fails.
     *
     * @experimental
     */
    public function listCompanies(ListCompaniesRequest $request, array $callOptions = []): PagedListResponse;

    /**
     * Updates specified company.
     *
     * The async variant is {@see CompanyServiceClient::updateCompanyAsync()} .
     *
     * @example samples/V4beta1/CompanyServiceClient/update_company.php
     *
     * @param UpdateCompanyRequest $request     A request to house fields associated with the call.
     * @param array                $callOptions {
     *     Optional.
     *
     *     @type RetrySettings|array $retrySettings
     *           Retry settings to use for this call. Can be a {@see RetrySettings} object, or an
     *           associative array of retry settings parameters. See the documentation on
     *           {@see RetrySettings} for example usage.
     * }
     *
     * @return Company
     *
     * @throws ApiException Thrown if the API call fails.
     *
     * @experimental
     */
    public function updateCompany(UpdateCompanyRequest $request, array $callOptions = []): Company;
}
