<?php
/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * GENERATED CODE WARNING
 * Generated by gapic-generator-php from the file
 * https://github.com/googleapis/googleapis/blob/master/google/cloud/talent/v4beta1/job_service.proto
 * Updates to the above are reflected here through a refresh process.
 *
 * @experimental
 */

namespace Google\Cloud\Talent\V4beta1\Client;

use Google\ApiCore\ApiException;
use Google\ApiCore\OperationResponse;
use Google\ApiCore\PagedListResponse;
use Google\ApiCore\RetrySettings;
use Google\Cloud\Talent\V4beta1\BatchCreateJobsRequest;
use Google\Cloud\Talent\V4beta1\BatchDeleteJobsRequest;
use Google\Cloud\Talent\V4beta1\BatchUpdateJobsRequest;
use Google\Cloud\Talent\V4beta1\CreateJobRequest;
use Google\Cloud\Talent\V4beta1\DeleteJobRequest;
use Google\Cloud\Talent\V4beta1\GetJobRequest;
use Google\Cloud\Talent\V4beta1\Job;
use Google\Cloud\Talent\V4beta1\JobOperationResult;
use Google\Cloud\Talent\V4beta1\ListJobsRequest;
use Google\Cloud\Talent\V4beta1\SearchJobsRequest;
use Google\Cloud\Talent\V4beta1\UpdateJobRequest;
use Google\LongRunning\Client\OperationsClient;
use Google\LongRunning\Operation;
use GuzzleHttp\Promise\PromiseInterface;

/**
 * Service Description: A service handles job management, including job CRUD, enumeration and search.
 *
 * This interface defines the methods available for calling the backing service
 * API.
 *
 * @experimental
 *
 * @method PromiseInterface<OperationResponse> batchCreateJobsAsync(BatchCreateJobsRequest $request, array $optionalArgs = [])
 * @method PromiseInterface<void> batchDeleteJobsAsync(BatchDeleteJobsRequest $request, array $optionalArgs = [])
 * @method PromiseInterface<OperationResponse> batchUpdateJobsAsync(BatchUpdateJobsRequest $request, array $optionalArgs = [])
 * @method PromiseInterface<Job> createJobAsync(CreateJobRequest $request, array $optionalArgs = [])
 * @method PromiseInterface<void> deleteJobAsync(DeleteJobRequest $request, array $optionalArgs = [])
 * @method PromiseInterface<Job> getJobAsync(GetJobRequest $request, array $optionalArgs = [])
 * @method PromiseInterface<PagedListResponse> listJobsAsync(ListJobsRequest $request, array $optionalArgs = [])
 * @method PromiseInterface<PagedListResponse> searchJobsAsync(SearchJobsRequest $request, array $optionalArgs = [])
 * @method PromiseInterface<PagedListResponse> searchJobsForAlertAsync(SearchJobsRequest $request, array $optionalArgs = [])
 * @method PromiseInterface<Job> updateJobAsync(UpdateJobRequest $request, array $optionalArgs = [])
 */
interface JobServiceClientInterface
{
    /**
     * Return an OperationsClient object with the same endpoint as $this.
     *
     * @return OperationsClient
     *
     * @experimental
     */
    public function getOperationsClient();

    /**
     * Resume an existing long running operation that was previously started by a long
     * running API method. If $methodName is not provided, or does not match a long
     * running API method, then the operation can still be resumed, but the
     * OperationResponse object will not deserialize the final response.
     *
     * @param string $operationName The name of the long running operation
     * @param string $methodName    The name of the method used to start the operation
     *
     * @return OperationResponse
     *
     * @experimental
     */
    public function resumeOperation($operationName, $methodName = null);

    /**
     * Begins executing a batch create jobs operation.
     *
     * The async variant is {@see JobServiceClient::batchCreateJobsAsync()} .
     *
     * @example samples/V4beta1/JobServiceClient/batch_create_jobs.php
     *
     * @param BatchCreateJobsRequest $request     A request to house fields associated with the call.
     * @param array                  $callOptions {
     *     Optional.
     *
     *     @type RetrySettings|array $retrySettings
     *           Retry settings to use for this call. Can be a {@see RetrySettings} object, or an
     *           associative array of retry settings parameters. See the documentation on
     *           {@see RetrySettings} for example usage.
     * }
     *
     * @return OperationResponse<JobOperationResult>
     *
     * @throws ApiException Thrown if the API call fails.
     *
     * @experimental
     */
    public function batchCreateJobs(BatchCreateJobsRequest $request, array $callOptions = []): OperationResponse;

    /**
     * Deletes a list of [Job][google.cloud.talent.v4beta1.Job]s by filter.
     *
     * The async variant is {@see JobServiceClient::batchDeleteJobsAsync()} .
     *
     * @example samples/V4beta1/JobServiceClient/batch_delete_jobs.php
     *
     * @param BatchDeleteJobsRequest $request     A request to house fields associated with the call.
     * @param array                  $callOptions {
     *     Optional.
     *
     *     @type RetrySettings|array $retrySettings
     *           Retry settings to use for this call. Can be a {@see RetrySettings} object, or an
     *           associative array of retry settings parameters. See the documentation on
     *           {@see RetrySettings} for example usage.
     * }
     *
     * @throws ApiException Thrown if the API call fails.
     *
     * @experimental
     */
    public function batchDeleteJobs(BatchDeleteJobsRequest $request, array $callOptions = []): void;

    /**
     * Begins executing a batch update jobs operation.
     *
     * The async variant is {@see JobServiceClient::batchUpdateJobsAsync()} .
     *
     * @example samples/V4beta1/JobServiceClient/batch_update_jobs.php
     *
     * @param BatchUpdateJobsRequest $request     A request to house fields associated with the call.
     * @param array                  $callOptions {
     *     Optional.
     *
     *     @type RetrySettings|array $retrySettings
     *           Retry settings to use for this call. Can be a {@see RetrySettings} object, or an
     *           associative array of retry settings parameters. See the documentation on
     *           {@see RetrySettings} for example usage.
     * }
     *
     * @return OperationResponse<JobOperationResult>
     *
     * @throws ApiException Thrown if the API call fails.
     *
     * @experimental
     */
    public function batchUpdateJobs(BatchUpdateJobsRequest $request, array $callOptions = []): OperationResponse;

    /**
     * Creates a new job.
     *
     * Typically, the job becomes searchable within 10 seconds, but it may take
     * up to 5 minutes.
     *
     * The async variant is {@see JobServiceClient::createJobAsync()} .
     *
     * @example samples/V4beta1/JobServiceClient/create_job.php
     *
     * @param CreateJobRequest $request     A request to house fields associated with the call.
     * @param array            $callOptions {
     *     Optional.
     *
     *     @type RetrySettings|array $retrySettings
     *           Retry settings to use for this call. Can be a {@see RetrySettings} object, or an
     *           associative array of retry settings parameters. See the documentation on
     *           {@see RetrySettings} for example usage.
     * }
     *
     * @return Job
     *
     * @throws ApiException Thrown if the API call fails.
     *
     * @experimental
     */
    public function createJob(CreateJobRequest $request, array $callOptions = []): Job;

    /**
     * Deletes the specified job.
     *
     * Typically, the job becomes unsearchable within 10 seconds, but it may take
     * up to 5 minutes.
     *
     * The async variant is {@see JobServiceClient::deleteJobAsync()} .
     *
     * @example samples/V4beta1/JobServiceClient/delete_job.php
     *
     * @param DeleteJobRequest $request     A request to house fields associated with the call.
     * @param array            $callOptions {
     *     Optional.
     *
     *     @type RetrySettings|array $retrySettings
     *           Retry settings to use for this call. Can be a {@see RetrySettings} object, or an
     *           associative array of retry settings parameters. See the documentation on
     *           {@see RetrySettings} for example usage.
     * }
     *
     * @throws ApiException Thrown if the API call fails.
     *
     * @experimental
     */
    public function deleteJob(DeleteJobRequest $request, array $callOptions = []): void;

    /**
     * Retrieves the specified job, whose status is OPEN or recently EXPIRED
     * within the last 90 days.
     *
     * The async variant is {@see JobServiceClient::getJobAsync()} .
     *
     * @example samples/V4beta1/JobServiceClient/get_job.php
     *
     * @param GetJobRequest $request     A request to house fields associated with the call.
     * @param array         $callOptions {
     *     Optional.
     *
     *     @type RetrySettings|array $retrySettings
     *           Retry settings to use for this call. Can be a {@see RetrySettings} object, or an
     *           associative array of retry settings parameters. See the documentation on
     *           {@see RetrySettings} for example usage.
     * }
     *
     * @return Job
     *
     * @throws ApiException Thrown if the API call fails.
     *
     * @experimental
     */
    public function getJob(GetJobRequest $request, array $callOptions = []): Job;

    /**
     * Lists jobs by filter.
     *
     * The async variant is {@see JobServiceClient::listJobsAsync()} .
     *
     * @example samples/V4beta1/JobServiceClient/list_jobs.php
     *
     * @param ListJobsRequest $request     A request to house fields associated with the call.
     * @param array           $callOptions {
     *     Optional.
     *
     *     @type RetrySettings|array $retrySettings
     *           Retry settings to use for this call. Can be a {@see RetrySettings} object, or an
     *           associative array of retry settings parameters. See the documentation on
     *           {@see RetrySettings} for example usage.
     * }
     *
     * @return PagedListResponse
     *
     * @throws ApiException Thrown if the API call fails.
     *
     * @experimental
     */
    public function listJobs(ListJobsRequest $request, array $callOptions = []): PagedListResponse;

    /**
     * Searches for jobs using the provided
     * [SearchJobsRequest][google.cloud.talent.v4beta1.SearchJobsRequest].
     *
     * This call constrains the
     * [visibility][google.cloud.talent.v4beta1.Job.visibility] of jobs present in
     * the database, and only returns jobs that the caller has permission to
     * search against.
     *
     * The async variant is {@see JobServiceClient::searchJobsAsync()} .
     *
     * @example samples/V4beta1/JobServiceClient/search_jobs.php
     *
     * @param SearchJobsRequest $request     A request to house fields associated with the call.
     * @param array             $callOptions {
     *     Optional.
     *
     *     @type RetrySettings|array $retrySettings
     *           Retry settings to use for this call. Can be a {@see RetrySettings} object, or an
     *           associative array of retry settings parameters. See the documentation on
     *           {@see RetrySettings} for example usage.
     * }
     *
     * @return PagedListResponse
     *
     * @throws ApiException Thrown if the API call fails.
     *
     * @experimental
     */
    public function searchJobs(SearchJobsRequest $request, array $callOptions = []): PagedListResponse;

    /**
     * Searches for jobs using the provided
     * [SearchJobsRequest][google.cloud.talent.v4beta1.SearchJobsRequest].
     *
     * This API call is intended for the use case of targeting passive job
     * seekers (for example, job seekers who have signed up to receive email
     * alerts about potential job opportunities), and has different algorithmic
     * adjustments that are targeted to passive job seekers.
     *
     * This call constrains the
     * [visibility][google.cloud.talent.v4beta1.Job.visibility] of jobs present in
     * the database, and only returns jobs the caller has permission to search
     * against.
     *
     * The async variant is {@see JobServiceClient::searchJobsForAlertAsync()} .
     *
     * @example samples/V4beta1/JobServiceClient/search_jobs_for_alert.php
     *
     * @param SearchJobsRequest $request     A request to house fields associated with the call.
     * @param array             $callOptions {
     *     Optional.
     *
     *     @type RetrySettings|array $retrySettings
     *           Retry settings to use for this call. Can be a {@see RetrySettings} object, or an
     *           associative array of retry settings parameters. See the documentation on
     *           {@see RetrySettings} for example usage.
     * }
     *
     * @return PagedListResponse
     *
     * @throws ApiException Thrown if the API call fails.
     *
     * @experimental
     */
    public function searchJobsForAlert(SearchJobsRequest $request, array $callOptions = []): PagedListResponse;

    /**
     * Updates specified job.
     *
     * Typically, updated contents become visible in search results within 10
     * seconds, but it may take up to 5 minutes.
     *
     * The async variant is {@see JobServiceClient::updateJobAsync()} .
     *
     * @example samples/V4beta1/JobServiceClient/update_job.php
     *
     * @param UpdateJobRequest $request     A request to house fields associated with the call.
     * @param array            $callOptions {
     *     Optional.
     *
     *     @type RetrySettings|array $retrySettings
     *           Retry settings to use for this call. Can be a {@see RetrySettings} object, or an
     *           associative array of retry settings parameters. See the documentation on
     *           {@see RetrySettings} for example usage.
     * }
     *
     * @return Job
     *
     * @throws ApiException Thrown if the API call fails.
     *
     * @experimental
     */
    public function updateJob(UpdateJobRequest $request, array $callOptions = []): Job;
}
