<?php
/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * GENERATED CODE WARNING
 * Generated by gapic-generator-php from the file
 * https://github.com/googleapis/googleapis/blob/master/tests/Integration/apis/compute_small/v1/compute_small.proto
 * Updates to the above are reflected here through a refresh process.
 */

namespace Google\Cloud\Compute\V1\Client;

use Google\ApiCore\ApiException;
use Google\ApiCore\OperationResponse;
use Google\ApiCore\PagedListResponse;
use Google\ApiCore\RetrySettings;
use Google\Cloud\Compute\V1\AggregatedListAddressesRequest;
use Google\Cloud\Compute\V1\DeleteAddressRequest;
use Google\Cloud\Compute\V1\InsertAddressRequest;
use Google\Cloud\Compute\V1\ListAddressesRequest;
use GuzzleHttp\Promise\PromiseInterface;

/**
 * Service Description:
 * Services
 *
 * The Addresses API.
 *
 * This interface defines the methods available for calling the backing service
 * API.
 *
 * @method PromiseInterface<PagedListResponse> aggregatedListAsync(AggregatedListAddressesRequest $request, array $optionalArgs = [])
 * @method PromiseInterface<OperationResponse> deleteAsync(DeleteAddressRequest $request, array $optionalArgs = [])
 * @method PromiseInterface<OperationResponse> insertAsync(InsertAddressRequest $request, array $optionalArgs = [])
 * @method PromiseInterface<PagedListResponse> listAsync(ListAddressesRequest $request, array $optionalArgs = [])
 */
interface AddressesClientInterface
{
    /**
     * Return an RegionOperationsClient object with the same endpoint as $this.
     *
     * @return RegionOperationsClient
     */
    public function getOperationsClient();

    /**
     * Resume an existing long running operation that was previously started by a long
     * running API method. If $methodName is not provided, or does not match a long
     * running API method, then the operation can still be resumed, but the
     * OperationResponse object will not deserialize the final response.
     *
     * @param string $operationName The name of the long running operation
     * @param string $methodName    The name of the method used to start the operation
     *
     * @return OperationResponse
     */
    public function resumeOperation($operationName, $methodName = null);

    /**
     * Retrieves an aggregated list of addresses.
     *
     * The async variant is {@see AddressesClient::aggregatedListAsync()} .
     *
     * @example samples/V1/AddressesClient/aggregated_list.php
     *
     * @param AggregatedListAddressesRequest $request     A request to house fields associated with the call.
     * @param array                          $callOptions {
     *     Optional.
     *
     *     @type RetrySettings|array $retrySettings
     *           Retry settings to use for this call. Can be a {@see RetrySettings} object, or an
     *           associative array of retry settings parameters. See the documentation on
     *           {@see RetrySettings} for example usage.
     * }
     *
     * @return PagedListResponse
     *
     * @throws ApiException Thrown if the API call fails.
     */
    public function aggregatedList(AggregatedListAddressesRequest $request, array $callOptions = []): PagedListResponse;

    /**
     * Deletes the specified address resource.
     *
     * The async variant is {@see AddressesClient::deleteAsync()} .
     *
     * @example samples/V1/AddressesClient/delete.php
     *
     * @param DeleteAddressRequest $request     A request to house fields associated with the call.
     * @param array                $callOptions {
     *     Optional.
     *
     *     @type RetrySettings|array $retrySettings
     *           Retry settings to use for this call. Can be a {@see RetrySettings} object, or an
     *           associative array of retry settings parameters. See the documentation on
     *           {@see RetrySettings} for example usage.
     * }
     *
     * @return OperationResponse
     *
     * @throws ApiException Thrown if the API call fails.
     */
    public function delete(DeleteAddressRequest $request, array $callOptions = []): OperationResponse;

    /**
     * Creates an address resource in the specified project by using the data included in the request.
     *
     * The async variant is {@see AddressesClient::insertAsync()} .
     *
     * @example samples/V1/AddressesClient/insert.php
     *
     * @param InsertAddressRequest $request     A request to house fields associated with the call.
     * @param array                $callOptions {
     *     Optional.
     *
     *     @type RetrySettings|array $retrySettings
     *           Retry settings to use for this call. Can be a {@see RetrySettings} object, or an
     *           associative array of retry settings parameters. See the documentation on
     *           {@see RetrySettings} for example usage.
     * }
     *
     * @return OperationResponse
     *
     * @throws ApiException Thrown if the API call fails.
     */
    public function insert(InsertAddressRequest $request, array $callOptions = []): OperationResponse;

    /**
     * Retrieves a list of addresses contained within the specified region.
     *
     * The async variant is {@see AddressesClient::listAsync()} .
     *
     * @example samples/V1/AddressesClient/list.php
     *
     * @param ListAddressesRequest $request     A request to house fields associated with the call.
     * @param array                $callOptions {
     *     Optional.
     *
     *     @type RetrySettings|array $retrySettings
     *           Retry settings to use for this call. Can be a {@see RetrySettings} object, or an
     *           associative array of retry settings parameters. See the documentation on
     *           {@see RetrySettings} for example usage.
     * }
     *
     * @return PagedListResponse
     *
     * @throws ApiException Thrown if the API call fails.
     */
    public function list(ListAddressesRequest $request, array $callOptions = []): PagedListResponse;
}
