permissions:
  contents: read

name: Lint

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    style:
        runs-on: ubuntu-latest
        name: PHP Style Check
        steps:
          - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
            with:
              persist-credentials: false
          - name: Setup PHP
            uses: shivammathur/setup-php@eb7c497e18156a6bbabfef1d3a82760b9eda3962 # v2
            with:
              php-version: '8.2'
          - name: Install dependencies
            run: composer global require "friendsofphp/php-cs-fixer:^3.0"
          - name: Run PHP CS Fixer
            run: ~/.composer/vendor/bin/php-cs-fixer fix --dry-run --diff

    static-analysis:
        runs-on: ubuntu-latest
        name: PHPStan Static Analysis
        steps:
          - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
            with:
              persist-credentials: false
          - name: Setup PHP
            uses: shivammathur/setup-php@eb7c497e18156a6bbabfef1d3a82760b9eda3962 # v2
            with:
              php-version: '8.4'
          - name: Run PHPStan
            run: |
              composer install -q
              composer global require "phpstan/phpstan:^1.8" -q
              ~/.composer/vendor/bin/phpstan analyse src --autoload-file=tests/Unit/autoload.php

    composer-audit:
        runs-on: ubuntu-latest
        name: Composer Audit
        steps:
          - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
            with:
              persist-credentials: false
          - name: Install PHP
            uses: shivammathur/setup-php@eb7c497e18156a6bbabfef1d3a82760b9eda3962 # v2
            with:
              php-version: '8.2'
          - name: Install dependencies
            run: composer --no-interaction --no-ansi --no-progress update
          - name: Audit dependencies
            run: composer audit --abandoned=fail

