permissions:
  contents: read

name: Lint

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    style:
        name: PHP Style Check
        uses: GoogleCloudPlatform/php-tools/.github/workflows/code-standards.yml@main # zizmor: ignore[unpinned-uses]
        with:
          path: src

    static-analysis:
        name: PHPStan Static Analysis
        uses: GoogleCloudPlatform/php-tools/.github/workflows/static-analysis.yml@main # zizmor: ignore[unpinned-uses]
        with:
          autoload-file: tests/Unit/autoload.php
