permissions:
  contents: read

name: Lint

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    style:
        name: PHP Style Check
        uses: GoogleCloudPlatform/php-tools/.github/workflows/code-standards.yml@c9ef4db634c55806c0a596e7278ff8ab62e0ca41 # v0.16.1
        with:
          path: src

    static-analysis:
        name: PHPStan Static Analysis
        uses: GoogleCloudPlatform/php-tools/.github/workflows/static-analysis.yml@c9ef4db634c55806c0a596e7278ff8ab62e0ca41 # v0.16.1
        with:
          autoload-file: tests/Unit/autoload.php

    composer-audit:
        runs-on: ubuntu-latest
        name: Composer Audit
        steps:
          - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
            with:
              persist-credentials: false
          - name: Install PHP
            uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
            with:
              php-version: '8.2'
          - name: Install dependencies
            run: composer --no-interaction --no-ansi --no-progress update
          - name: Audit dependencies
            run: composer audit --abandoned=fail

