name: Release Checks
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ['main']
permissions:
  contents: read
jobs:
    next-release-label-check:
        name: Check for "next release" label
        uses: GoogleCloudPlatform/php-tools/.github/workflows/release-checks.yml@main
        if: github.event.pull_request.user.login == 'release-please[bot]'
        with:
            next-release-label-check: false
